<a href="https://colab.research.google.com/github/spike8888/Data_science_bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

### Norma wektora, długość wektora w R^2

In [2]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [3]:
# długość wektora
np.linalg.norm(v1)

4.0

In [4]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [5]:
# długość wektora
np.linalg.norm(v1)

4.123105625617661

### Norma euklidesowa w Rn

In [6]:
# długość wektora 3D
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

### Odleglosc dwoch punktow na plaszczyznie

In [7]:
# ksztalt trojkata prostokatnego
p = np.array([3, 0])
q = np.array([0, 4])

# dlugosc bedzie dlugoscia pierwiastka przeciwprostokatnej
np.linalg.norm(p - q)

5.0

### Odleglosc dwoch punktow w przestrzeni Rn

In [8]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### Mnożenie macierzy

A - macierz wymiaru m x n

B - macierz wymiaru n x p

C = AB

C - macierz wymiaru m x p

Aby móc pomnozyć dwie macierze liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy
Mnożenie macierzy nie jest przemienne! Tzn AB != BA

### Przyklad 1

In [9]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


X macierz 2x2

Y macierz 2x1

In [10]:
Z = X.dot(Y)
Z

array([[ 2],
       [-6]])

In [11]:
Z.shape

(2, 1)

### Przyklad 2

In [12]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


X macierz 2x3

Y macierz 3x3

Z macierz 2x3

In [13]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

### Wyznacznik macierzy

In [17]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

### Ślad macirzy

In [18]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

### Macierz jednostkowa

In [19]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Macierz odwrotna

In [22]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [30]:
np.set_printoptions(precision=None, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [31]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

In [32]:
A

array([[ 2,  4],
       [-1,  3]])

In [33]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [34]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### Rozwiązywanie układów równań

2x + 4y = 10

x - y = -1

Rozwiazanie:

x = 1

y = 2

In [36]:
# macierz wspolczynnikow
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [38]:
# macierz wyrazow wolnych
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [39]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.16666667  0.66666667]
 [ 0.16666667 -0.33333333]]


In [40]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [42]:
X.shape

(2, 1)