<a href="https://colab.research.google.com/github/spike8888/Data_science_bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Funkcje statystyczne

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
price = np.array([[12.4, 12.8, 11.9, 12.6, 1000],
                  [12.5, 13.0, 11.7, 12.2, 2000],
                  [12.2, 13.4, 12.2, 13.2, 1500]])

print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [3]:
# funkcja sum()
price.sum()

4650.1

In [4]:
# sumowanie po wierszach lub kolumnach
# axis = 0 - po kolumnach
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
# axis = 1 - po wierszach
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [6]:
np.sum(price)

4650.1

In [7]:
np.min(price)

11.7

In [8]:
np.max(price)

2000.0

In [9]:
np.median(price)

12.6

In [11]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [13]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [15]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [16]:
np.set_printoptions(precision=4, suppress=True)

In [17]:
np.var(price, axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])